name: Demo Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "* 15 * * *"
  push:
    branches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hej BMW 🚙, Ayan This side!"
  list-files:
    runs-on: ubuntu-latest
    needs: demo
    steps:
      - uses: actions/checkout@v4
      - run: ls -l
